# Generated by Django 5.0 on 2023-12-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('contentdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mock.contentdetail')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=('mock.contentdetail',),
        ),
        migrations.CreateModel(
            name='ContentStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.contentdetail')),
                ('content_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.product'),
        ),
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('contentdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mock.contentdetail')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mock.product')),
            ],
            bases=('mock.contentdetail',),
        ),
    ]
