# Generated by Django 5.0 on 2023-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0002_contentcategory_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
