# Generated by Django 5.0 on 2023-12-29 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_page_contentdetail_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdetail',
            name='contents',
        ),
        migrations.CreateModel(
            name='ContentStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.contentdetail')),
                ('content_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.content')),
            ],
        ),
    ]
